### ISSUE TITLE
Unable to validate sample API's for front end and resource server on my machine

### ISSUE THREAD

**Issue by Rajshah1897** [okta/samples-java-spring#69] opened 2020-09-14 21:44 UTC
@bdemers @arvindkrishnakumar-okta @vijetmahabaleshwar-okta  Continue from https://github.com/okta/samples-java-spring/issues/66

@vijetmahabaleshwar-okta Thats was I asked before the user constant screen not coming on my SPA settings. Please see the screenshot.

image

Also only logout button on my screen I can see that after run above commands (https://github.com/okta/samples-java-spring/issues/66) in the terminal.

image

Do we need to do anything in this screen as below screens?

image

image

Thanks,
Raj Shah

**Comment by bdemers** [comment] 2020-09-14 21:45
Duplicate of #66

**Closed by bdemers** 2020-09-14 21:45 UTC
